# Project: Swig-Tutorial
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = example.o example.o
LINKOBJ  = example.o example.o
LIBS     = -L"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/lib" -L"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/include" -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/include" -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/sjoshia/Documents/libraries/boost_1_67_0"
BIN      = Swig-Tutorial.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11 -DMS_WIN64
CFLAGS   = $(INCS) -std=gnu++11 -DMS_WIN64
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

example.o: example.cpp
	$(CPP) -c example.cpp -o example.o $(CXXFLAGS)
